In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import billboard

In [4]:
bb1_csv = '../Resources/billboard_1_year.csv'
bb1_df = pd.read_csv(bb1_csv)
bb1_df

,Unnamed: 0,artist,title,lastPos,rank,weeks,date
0,0,Shawn Mendes & Camila Cabello,Senorita,2,1,9,2019-08-31
1,1,Billie Eilish,Bad Guy,1,2,21,2019-08-31
2,2,Lizzo,Truth Hurts,4,3,16,2019-08-31
3,3,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,3,4,25,2019-08-31
4,4,Lil Tecca,Ran$om,8,5,12,2019-08-31
...,...,...,...,...,...,...,...
5195,95,Wiz Khalifa Featuring Swae Lee,Hopeless Romantic,0,96,3,2018-09-08
5196,96,Juice WRLD Featuring Lil Uzi Vert,Wasted,0,97,6,2018-09-08
5197,97,"Khalid, Ty Dolla $ign & 6LACK",OTW,0,98,15,2018-09-08
5198,98,Becky G + Natti Natasha,Sin Pijama,98,99,12,2018-09-08
5199,99,Childish Gambino,This Is America,95,100,17,2018-09-08

In [5]:
search_1 = bb1_df[bb1_df['rank']==1]
date_groupby = search_1.groupby(['date'])
testing = date_groupby.head(100)
testing

,Unnamed: 0,artist,title,lastPos,rank,weeks,date
0,0,Shawn Mendes & Camila Cabello,Senorita,2,1,9,2019-08-31
100,0,Billie Eilish,Bad Guy,2,1,20,2019-08-24
200,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,23,2019-08-17
300,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,22,2019-08-10
400,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,21,2019-08-03
500,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,20,2019-07-27
600,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,19,2019-07-20
700,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,18,2019-07-13
800,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,17,2019-07-06
900,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,16,2019-06-29
1000,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,15,2019-06-22
1100,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,14,2019-06-15
1200,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,13,2019-06-08
1300,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,12,2019-06-01
1400,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,11,2019-05-25
1500,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,10,2019-05-18
1600,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,9,2019-05-11
1700,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,8,2019-05-04
1800,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,7,2019-04-27
1900,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,6,2019-04-20
2000,0,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,15,1,5,2019-04-13
2100,0,Ariana Grande,7 Rings,1,1,10,2019-04-06
2200,0,Ariana Grande,7 Rings,1,1,9,2019-03-30
2300,0,Ariana Grande,7 Rings,2,1,8,2019-03-23
2400,0,Jonas Brothers,Sucker,0,1,1,2019-03-16
2500,0,Lady Gaga & Bradley Cooper,Shallow,21,1,22,2019-03-09
2600,0,Ariana Grande,7 Rings,1,1,5,2019-03-02
2700,0,Ariana Grande,7 Rings,1,1,4,2019-02-23
2800,0,Ariana Grande,7 Rings,1,1,3,2019-02-16
2900,0,Ariana Grande,7 Rings,1,1,2,2019-02-09
3000,0,Ariana Grande,7 Rings,0,1,1,2019-02-02
3100,0,Halsey,Without Me,2,1,15,2019-01-26
3200,0,Post Malone & Swae Lee,Sunflower (Spider-Man: Into The Spider-Verse),3,1,12,2019-01-19
3300,0,Halsey,Without Me,2,1,13,2019-01-12
3400,0,Ariana Grande,"Thank U, Next",1,1,8,2019-01-05
3500,0,Ariana Grande,"Thank U, Next",1,1,7,2018-12-29
3600,0,Ariana Grande,"Thank U, Next",1,1,6,2018-12-22
3700,0,Ariana Grande,"Thank U, Next",2,1,5,2018-12-15
3800,0,Travis Scott,Sicko Mode,2,1,17,2018-12-08
3900,0,Ariana Grande,"Thank U, Next",1,1,3,2018-12-01
4000,0,Ariana Grande,"Thank U, Next",1,1,2,2018-11-24
4100,0,Ariana Grande,"Thank U, Next",0,1,1,2018-11-17
4200,0,Maroon 5 Featuring Cardi B,Girls Like You,1,1,23,2018-11-10
4300,0,Maroon 5 Featuring Cardi B,Girls Like You,1,1,22,2018-11-03
4400,0,Maroon 5 Featuring Cardi B,Girls Like You,1,1,21,2018-10-27
4500,0,Maroon 5 Featuring Cardi B,Girls Like You,1,1,20,2018-10-20
4600,0,Maroon 5 Featuring Cardi B,Girls Like You,1,1,19,2018-10-13
4700,0,Maroon 5 Featuring Cardi B,Girls Like You,1,1,18,2018-10-06
4800,0,Maroon 5 Featuring Cardi B,Girls Like You,2,1,17,2018-09-29
4900,0,Drake,In My Feelings,1,1,11,2018-09-22
5000,0,Drake,In My Feelings,1,1,10,2018-09-15
5100,0,Drake,In My Feelings,1,1,9,2018-09-08

In [32]:
drop_test = testing.drop(columns='Unnamed: 0')
drop_test

,artist,title,lastPos,rank,weeks,date
0,Shawn Mendes & Camila Cabello,Senorita,2,1,9,2019-08-31
100,Billie Eilish,Bad Guy,2,1,20,2019-08-24
200,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,23,2019-08-17
300,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,22,2019-08-10
400,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,21,2019-08-03
500,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,20,2019-07-27
600,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,19,2019-07-20
700,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,18,2019-07-13
800,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,17,2019-07-06
900,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,16,2019-06-29
1000,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,15,2019-06-22
1100,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,14,2019-06-15
1200,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,13,2019-06-08
1300,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,12,2019-06-01
1400,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,11,2019-05-25
1500,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,10,2019-05-18
1600,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,9,2019-05-11
1700,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,8,2019-05-04
1800,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,7,2019-04-27
1900,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,6,2019-04-20
2000,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,15,1,5,2019-04-13
2100,Ariana Grande,7 Rings,1,1,10,2019-04-06
2200,Ariana Grande,7 Rings,1,1,9,2019-03-30
2300,Ariana Grande,7 Rings,2,1,8,2019-03-23
2400,Jonas Brothers,Sucker,0,1,1,2019-03-16
2500,Lady Gaga & Bradley Cooper,Shallow,21,1,22,2019-03-09
2600,Ariana Grande,7 Rings,1,1,5,2019-03-02
2700,Ariana Grande,7 Rings,1,1,4,2019-02-23
2800,Ariana Grande,7 Rings,1,1,3,2019-02-16
2900,Ariana Grande,7 Rings,1,1,2,2019-02-09
3000,Ariana Grande,7 Rings,0,1,1,2019-02-02
3100,Halsey,Without Me,2,1,15,2019-01-26
3200,Post Malone & Swae Lee,Sunflower (Spider-Man: Into The Spider-Verse),3,1,12,2019-01-19
3300,Halsey,Without Me,2,1,13,2019-01-12
3400,Ariana Grande,"Thank U, Next",1,1,8,2019-01-05
3500,Ariana Grande,"Thank U, Next",1,1,7,2018-12-29
3600,Ariana Grande,"Thank U, Next",1,1,6,2018-12-22
3700,Ariana Grande,"Thank U, Next",2,1,5,2018-12-15
3800,Travis Scott,Sicko Mode,2,1,17,2018-12-08
3900,Ariana Grande,"Thank U, Next",1,1,3,2018-12-01
4000,Ariana Grande,"Thank U, Next",1,1,2,2018-11-24
4100,Ariana Grande,"Thank U, Next",0,1,1,2018-11-17
4200,Maroon 5 Featuring Cardi B,Girls Like You,1,1,23,2018-11-10
4300,Maroon 5 Featuring Cardi B,Girls Like You,1,1,22,2018-11-03
4400,Maroon 5 Featuring Cardi B,Girls Like You,1,1,21,2018-10-27
4500,Maroon 5 Featuring Cardi B,Girls Like You,1,1,20,2018-10-20
4600,Maroon 5 Featuring Cardi B,Girls Like You,1,1,19,2018-10-13
4700,Maroon 5 Featuring Cardi B,Girls Like You,1,1,18,2018-10-06
4800,Maroon 5 Featuring Cardi B,Girls Like You,2,1,17,2018-09-29
4900,Drake,In My Feelings,1,1,11,2018-09-22
5000,Drake,In My Feelings,1,1,10,2018-09-15
5100,Drake,In My Feelings,1,1,9,2018-09-08

In [35]:
drop_test_df = pd.DataFrame(drop_test)
drop_test_df

,artist,title,lastPos,rank,weeks,date
0,Shawn Mendes & Camila Cabello,Senorita,2,1,9,2019-08-31
100,Billie Eilish,Bad Guy,2,1,20,2019-08-24
200,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,23,2019-08-17
300,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,22,2019-08-10
400,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,21,2019-08-03
500,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,20,2019-07-27
600,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,19,2019-07-20
700,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,18,2019-07-13
800,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,17,2019-07-06
900,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,16,2019-06-29
1000,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,15,2019-06-22
1100,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,14,2019-06-15
1200,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,13,2019-06-08
1300,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,12,2019-06-01
1400,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,11,2019-05-25
1500,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,10,2019-05-18
1600,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,9,2019-05-11
1700,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,8,2019-05-04
1800,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,7,2019-04-27
1900,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,1,1,6,2019-04-20
2000,Lil Nas X Featuring Billy Ray Cyrus,Old Town Road,15,1,5,2019-04-13
2100,Ariana Grande,7 Rings,1,1,10,2019-04-06
2200,Ariana Grande,7 Rings,1,1,9,2019-03-30
2300,Ariana Grande,7 Rings,2,1,8,2019-03-23
2400,Jonas Brothers,Sucker,0,1,1,2019-03-16
2500,Lady Gaga & Bradley Cooper,Shallow,21,1,22,2019-03-09
2600,Ariana Grande,7 Rings,1,1,5,2019-03-02
2700,Ariana Grande,7 Rings,1,1,4,2019-02-23
2800,Ariana Grande,7 Rings,1,1,3,2019-02-16
2900,Ariana Grande,7 Rings,1,1,2,2019-02-09
3000,Ariana Grande,7 Rings,0,1,1,2019-02-02
3100,Halsey,Without Me,2,1,15,2019-01-26
3200,Post Malone & Swae Lee,Sunflower (Spider-Man: Into The Spider-Verse),3,1,12,2019-01-19
3300,Halsey,Without Me,2,1,13,2019-01-12
3400,Ariana Grande,"Thank U, Next",1,1,8,2019-01-05
3500,Ariana Grande,"Thank U, Next",1,1,7,2018-12-29
3600,Ariana Grande,"Thank U, Next",1,1,6,2018-12-22
3700,Ariana Grande,"Thank U, Next",2,1,5,2018-12-15
3800,Travis Scott,Sicko Mode,2,1,17,2018-12-08
3900,Ariana Grande,"Thank U, Next",1,1,3,2018-12-01
4000,Ariana Grande,"Thank U, Next",1,1,2,2018-11-24
4100,Ariana Grande,"Thank U, Next",0,1,1,2018-11-17
4200,Maroon 5 Featuring Cardi B,Girls Like You,1,1,23,2018-11-10
4300,Maroon 5 Featuring Cardi B,Girls Like You,1,1,22,2018-11-03
4400,Maroon 5 Featuring Cardi B,Girls Like You,1,1,21,2018-10-27
4500,Maroon 5 Featuring Cardi B,Girls Like You,1,1,20,2018-10-20
4600,Maroon 5 Featuring Cardi B,Girls Like You,1,1,19,2018-10-13
4700,Maroon 5 Featuring Cardi B,Girls Like You,1,1,18,2018-10-06
4800,Maroon 5 Featuring Cardi B,Girls Like You,2,1,17,2018-09-29
4900,Drake,In My Feelings,1,1,11,2018-09-22
5000,Drake,In My Feelings,1,1,10,2018-09-15
5100,Drake,In My Feelings,1,1,9,2018-09-08

In [48]:
new_df = drop_test.groupby(['artist'])
avg_rank = new_df['rank'].sum()
summary = pd.DataFrame({'Avg Rank': avg_rank})
summary

                                     Avg Rank
artist
Ariana Grande                              15
Billie Eilish                               1
Drake                                       3
Halsey                                      2
Jonas Brothers                              1
Lady Gaga & Bradley Cooper                  1
Lil Nas X Featuring Billy Ray Cyrus        19
Maroon 5 Featuring Cardi B                  7
Post Malone & Swae Lee                      1
Shawn Mendes & Camila Cabello               1
Travis Scott                                1

In [ ]:
.sum().groupby('artist').cumsum()
#cumsum_df = drop_test.groupby(['rank']).sum().groupby(['artist']).cumsum()